- id: black-formatter
  name: black formatter
  entry: scripts/black-formatter.sh
  language: script
  types: [python]

- id: flake8
  name: flake8 linter
  entry: flake8
  language: system
  files: \*.py
